---
- name: keyring
  ansible.builtin.get_url:
    url: "{{ antigravity_repo_key | default('https://us-central1-apt.pkg.dev/doc/repo-signing-key.gpg') }}"
    dest: /etc/apt/keyrings/antigravity-repo-key.asc
    mode: "0644"
    force: true
  become: true
  tags: admin

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/antigravity-repo-key.asc] {{ antigravity_repo_url | default('https://us-central1-apt.pkg.dev/projects/antigravity-auto-updater-dev/ antigravity-debian main') }}"
    filename: antigravity
    state: present
  become: true
  tags: admin

- name: package
  ansible.builtin.package:
    name: antigravity
  become: true
  tags: admin
