---
- name: script
  ansible.builtin.get_url:
    url: https://d2lang.com/install.sh
    dest: /tmp/d2lang-install.sh
    mode: "0755"
  tags: admin

- name: install
  ansible.builtin.command:
    cmd: /tmp/d2lang-install.sh
  args:
    creates: /usr/local/bin/d2
  become: true
  tags: admin
