---
- name: package
  ansible.builtin.package:
    name: "{{ 'fonts-firacode' if ansible_facts['distribution'] != 'MacOSX' else 'font-fira-code' }}"
  when: ansible_facts['distribution'] != 'MacOSX'
  become: true
  tags: admin

- name: cache
  ansible.builtin.command: fc-cache -fv
  when: ansible_facts['distribution'] != 'MacOSX'
  ignore_errors: true
  tags: user
